site_title: Victoria Wonnacott
site_email: vicwonn@gmail.com
url_facebook: https://www.facebook.com/victoria.wonnacott.5
url_instagram: https://www.instagram.com/vicwondot/
url_gallery: https://www.duranmashaalgallery.com/victoria-wonnacott/
url_archive: https://archive.vicwon.com
