---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _projects
  label: Projects
  create: documents
  match: "*"
  templates:
  - projects
- type: jekyll-pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - about
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
